name: particletracking
channels:
    - conda-forge
    - teokem
dependencies:
    - numpy
    - scipy
    - pandas
    - matplotlib
    - trackpy=0.4
    - pims
    - jupyter
    - notebook
    - ffmpeg
    - mdtraj
    - faunus
